#! /bin/bash

if [ "$1" = "" ]
then
	echo -e "Use : $0 <file_name>"
	exit 3
fi


if [ -c $1 ]
then
	echo "OK : $1 is a character device"
	exit 0
else
	echo "CRITICAL : $1 is NOT a character device"
	exit 2
fi
